version: '3'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: